.github/workflows/backend.yml
.github/workflows/frontend.yml
backend/src/app.service.ts
backend/src/main.ts

should be able to run the thing now on protected branches

fix(workflows): update name to be able to run the workflow automatically

---

Frontend/components/inputField/InputField.vue
Frontend/components/inputField/inputField.test.js

Initially it only emitted on element blur. Now it will emit the value on change without any delays

SCRUM 75: Nuxt Fe: update input field to handle v model

---

backend/OpenAPI.json
backend/README.md
backend/package-lock.json
backend/package.json
backend/src/app.module.ts
backend/src/main.ts
backend/src/modules/users/dto/create-user.dto.ts
backend/src/modules/users/dto/update-user.dto.ts
backend/src/modules/users/dto/user-tag.dto.ts
backend/src/modules/users/dto/user-with-relations.dto.ts
backend/src/modules/users/entities/user.entity.ts
backend/src/modules/users/users.controller.spec.ts
backend/src/modules/users/users.controller.ts
backend/src/modules/users/users.module.ts
backend/src/modules/users/users.service.spec.ts
backend/src/modules/users/users.service.ts

- Implement complete user CRUD endpoints (create, read, update, delete)
- Configure class-validator and class-transformer for request validation
- Add search functionality for LastName, FirstName, Tag_Id and Tag_Ids

feat(backend): Add CRUD operations for users module (SCRUM-71)

---

Frontend/components/TagSelector/TagSelector.test.js
Frontend/components/TagSelector/TagSelector.vue

Only added the tag selector component. nothing else

Scrum-87: Nuxt FE: create tag selector component

---

backend/.gitignore
backend/README.md
backend/package.json
backend/src/main.ts
backend/src/modules/users/users.controller.spec.ts
backend/src/modules/users/users.module.ts
backend/src/modules/users/users.repository.spec.ts
backend/src/modules/users/users.repository.ts
backend/src/modules/users/users.service.spec.ts
backend/src/modules/users/users.service.ts

* Added a new `UsersRepository` class to encapsulate all db operations related to users, (`backend/src/modules/users/users.repository.ts`).
* Updated the `UsersModule` to include `UsersRepository` in its providers and exports
* Refactored `users.controller.specs.ts` tests file to use a mock `UsersService`, eliminating direct database dependencies and improving test isolation (`backend/src/modules/users/users.controller.spec.ts`).
* Refactored `users.service.specs.ts` & `users.repository.specs.ts` tests file tests file similar to controller
* Added comprehensive test cases for all major controller, service and repo methods (`backend/src/modules/users/users.controller.spec.ts`).

Scrum 86 nest move all database interaction from services

---

Frontend/components/CardStack/CardStack.vue
Frontend/components/CustomTag/CustomTag.vue
Frontend/components/SupervisorCard/SupervisorCard.test.js
Frontend/components/SupervisorCard/SupervisorCard.vue
Frontend/package.json

- Previously, the Tag did not render correctly, despite passing all the required props. This now got fixed by correctly using static keys in the class Object. 
- The tags also have a new `muted` property, which make the colors in transparent variants have less opacity
- The tags now throw errors when an invalid color is used (only daisy colors + `base-content` is allowed, to an extent)
- The Tags in the Supervisor Card got adjusted accordingly
- The Supervisor Card is not more responsive and has an additional `full-width` property (boolean, default false), which can be toggled to make the card span the full width of the parent container (up to a breakpoint limit). This is useful for mobile responsiveness.
- The `lName`and `fName` properties are now called `firsName`/ `lastName` to be more …

fix(frontend): fix tag not rendering correctly, fix SupervisorCard responsiveness (SCRUM-96)

---

Frontend/components/ActionCard/ActionCard.test.js
Frontend/components/ActionCard/ActionCard.vue

This pull request introduces a new `ActionCard` Vue component and its corresponding test suite. The changes include the implementation of the component's functionality, props, and event handling, as well as comprehensive unit tests to ensure proper behavior.
* [`Frontend/components/ActionCard/ActionCard.vue`](diffhunk://#diff-ca2ef68aac61b76d8966be8f8adf079a5ffa365522367bf9e4b78cd34553d389R1-R63): Added the `ActionCard` component with props for `buttonText`, `cardType`, `action`, and `headerText`. The component includes a slot for custom content, a button with customizable text and style, and emits an `action` event when the button is clicked. Validation for `cardType` ensures only valid values (`"default"` or `"primary"`) are accepted.
* …

Scrum 85 nuxt fe create action card builder component

---

backend/OpenAPI.json
backend/src/common/exceptions/exceptions.module.ts
backend/src/common/logging/winston-logger.service.ts
backend/src/modules/tags/entities/tag-similarity.entity.ts
backend/src/modules/tags/entities/tag.entity.ts
backend/src/modules/tags/tags.controller.ts
backend/src/modules/users/dto/create-user.dto.ts
backend/src/modules/users/dto/set-user-tags.dto.ts
backend/src/modules/users/dto/update-user.dto.ts
backend/src/modules/users/entities/user-block.entity.ts
backend/src/modules/users/entities/user-with-relations.entity.ts
backend/src/modules/users/entities/user.entity.ts
backend/src/modules/users/users.controller.spec.ts
backend/src/modules/users/users.controller.ts
backend/src/modules/users/users.repository.spec.ts
backend/src/modules/users/users.repository.ts
backend/src/modules/users/users.service.spec.ts
backend/src/modules/users/users.service.ts

- Removed role parameter from CreateUserDto and UpdateUserDto
- Added is_registered parameter to UpdateUserDto to enable setting it, when signing up supervisors
- Fixed user creation flow by automatically setting is_registered=true
- Added findUserByEmail functionality for login flow
- Added tests for new and modified functionality

fix(backend): Set is_registered and hardcode STUDENT role (SCRUM-103)

---

Frontend/components/BottomNav/BottomNav.test.ts
Frontend/components/BottomNav/BottomNav.vue
Frontend/nuxt.config.js
Frontend/package-lock.json
Frontend/plugins/fontawesome.js

Adds the BottomNav from the figma design. The only difference is the Dashboard Icon because I didnt find a similar one, so I used "home" instead. I can change it tho if theres a better one. 
Showcase:
For testing, put this in the index.vue:
```vue
<template>
<div class="flex flex-col items-center px-2 max-w-full">
<div class="min-h-screen flex flex-col max-w-7xl w-full">
<AppHeader show-user show-search/>
<StatusBar :step=1 class="mt-4"/>
<div class="my-auto mx-auto max-w-7xl w-full">
<ActionCard
button-text="Start Matching!"
card-type="primary"
>
<div class="flex flex-col items-center my-8" >
<CardStack>
<SupervisorCard
:current-capacity=12
:max-capacity=24
:similarity-score=69
:pending-amount=7
:tags="['Machine Learning', 'Artificial Intelligence', 'Web Development']"
last-name="Seidl" …
```

feat(frontend): add BottomNav component (SCRUM-100)

---

backend/OpenAPI.json
backend/src/app.module.ts
backend/src/modules/matching/entity/match.entity.ts
backend/src/modules/matching/matching.controller.ts
backend/src/modules/matching/matching.module.ts
backend/src/modules/matching/matching.service.spec.ts
backend/src/modules/matching/matching.service.ts
backend/src/modules/supervisors/dto/update-supervisor.dto.ts
backend/src/modules/supervisors/supervisors.service.ts

Matching algorithm that calculates compatibility scores based on tags, priorities, and semantic similarity scores.
- Tag-based matching with priority weighting
- Semantic similarity score fetching between related fields
- Efficient caching system with 24-hour expiration
- Normalized scoring (0-1 range)
- Endpoint at GET /match/:userId for retrieving matches by user id of a student
- Created `MatchingService` with bidirectional similarity cache (example : ai to machine learning - machine learning to ai)
- Added unit tests
- Handled edge cases (missing tags, priority changes)
- Optimized API calls with prefetching

Scrum 48 nest be implement matching algorithm

---

Frontend/components/Toast/Toast.test.ts
Frontend/components/Toast/Toast.vue
Frontend/plugins/fontawesome.js

Create Toast Modal
```vue
<template>
<div class="min-h-screen flex flex-col max-w-7xl w-full">
<Toast
button-text="close"
duration="10000"
message="Chat Request has been Sent successfully"
type="success"
@button-click="console.log('Button clicked')"
/>
<AppHeader show-search show-user/>
<StatusBar :step=1 class="mt-4"/>
<div class="my-auto mx-auto max-w-7xl w-full p-12">
<ActionCard
button-text="Start Matching!"
card-type="primary"
>
<div class="flex flex-col w-full items-center  p-3"/>
</ActionCard>
</div>
<div class="max-w-7xl w-full">
<BottomNav
:active-route="dummyRoute"
:always-show-labels="false"
@navigate="navigate"
/>
</div>
</div>
</template>
<script setup>
import {ref} from 'vue';
import BottomNav from "../components/BottomNav/BottomNav.vue";
import AppHeader from …
```

feature(frontend) Scrum 114 nuxt fe create toast component

---

backend/OpenAPI.json
backend/src/modules/matching/entity/match.entity.ts
backend/src/modules/matching/matching.service.spec.ts
backend/src/modules/matching/matching.service.ts

Just added supervisor name and last name in the match array of objects and changed using the supervisor id to the user id of a supervisor.

chore(backend): added name last name of supervisor  (SCRUM-119)

---

Frontend/components/AdminHeader/AdminHeader.test.ts
Frontend/components/AdminHeader/AdminHeader.vue
Frontend/pages/dashboard.vue

```vue
<template>
<div class="min-h-screen flex flex-col max-w-7xl w-full">
<AdminHeader variant="default"/>
<AdminHeader variant="download"/>
<AdminHeader variant="upload"/>
<AdminHeader variant="delete"/>
<StatusBar :step=1 class="mt-4"/>
<div class="my-auto mx-auto max-w-7xl w-full p-12">
<ActionCard
button-text="Start Matching!"
card-type="primary"
>
<div class="flex flex-col w-full items-center  p-3"/>
</ActionCard>
</div>
<div class="max-w-7xl w-full">
<BottomNav
:active-route="dummyRoute"
:always-show-labels="false"
@navigate="navigate"
/>
</div>
</div>
</template>
<script setup>
import {ref} from 'vue';
import BottomNav from "../components/BottomNav/BottomNav.vue";
import StatusBar from "../components/StatusBar/StatusBar.vue";
import ActionCard from …
```

feature(frontend): create admin app header (SCRUM-115)

---

Frontend/assets/css/app.css
Frontend/components/ConfirmationModal/ConfirmationModal.test.js
Frontend/components/ConfirmationModal/ConfirmationModal.vue
Frontend/plugins/fontawesome.js

This PR creates the Confirmation modal and also updates the daisyUI config, as we had a mistake these (depth and noise effect was not wanted)
You can test the modal by putting the following code in the index.vue. It's not demonstrating every use case, but it's 1AM and I want to sleep
```vue
<template>
<div class="flex flex-col items-center px-2 max-w-full">
<div>
<h1 class="text-2xl font-bold">Swipeable Supervisor Cards with confirmation modals</h1>
<p class="text-sm">Swipe left to reject, swipe right to send a supervision request.</p>
<div v-for="item in supervisors" :key="item.id">
<SwipeContainer
v-if="!dismissQueue.includes(item.id) && !supervisionRequestQueue.includes(item.id)"
:ref="el => swipeContainers[item.id] = el"
@swipe-right="showModal(`confirmation-modal-${item.id}`)" …
```

feat(frontend): Create confirmation modal (SCRUM-124)

---

Frontend/components/ConfirmationExport/ConfirmationExport.vue
Frontend/package-lock.json
Frontend/package.json
Frontend/utils/imageCreationHelpers.ts

index.vue:
```vue
<template>
<div>
<ConfirmationExport
:canvas-id="canvasId"
:student-name="data.studentName"
:student-email="data.studentEmail"
:supervisor-name="data.supervisorName"
:supervisor-email="data.supervisorEmail"
:accepted-date="data.acceptedDate"
:confirmation-url="data.confirmationUrl"
/>
<CustomButton text="Download Confirmation" @click="downloadImageFromCanvas(canvasId)" />
</div>
</template>
<script setup lang="ts">
import {downloadImageFromCanvas} from "~/utils/imageCreationHelpers";
const canvasId = "confirmation-canvas-69";
const data = {
studentName: "Alice Example",
studentEmail: "alice@example.com",
supervisorName: "Dr. Bob Scholar",
supervisorEmail: "bob@university.edu",
acceptedDate: "2025-05-14",
confirmationUrl: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
} …
```

feat(frontend): Add confirmation export with canvas and download Util Function (SCRUM-128)

---

Frontend/components/ProfileDescription/ProfilDescription.test.ts
Frontend/components/ProfileDescription/ProfileDescription.vue
Frontend/plugins/fontawesome.js

index.vue:
```vue
<template>
<ProfileDescription
headline="Bio"
content="Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum."
/>
</template>
```

feat(frontend): create bio description component (SCRUM-137)

---

Frontend/assets/css/app.css
Frontend/components/UnsafeFileInput/UnsafeFileInput.vue

Code can be tested here:
```vue
<script lang="ts" setup>
import UnsafeFileInput from "~/components/UnsafeFileInput/UnsafeFileInput.vue";
definePageMeta({
layout: "landing-layout",
});
</script>
<template>
<div>
<AdminHeader
header-text="Upload"
variant="upload"
/>
<div class="flex flex-col gap-4 p-8">
<UnsafeFileInput
button-color="info"
button-text="Upload"
button-width="block"
description="this updates the supervisors & their available slots"
file-type="csv"
title="Supervisors"
/>
<UnsafeFileInput
button-color="info"
button-text="Upload"
button-width="block"
description="Upload some fuckting tags"
file-name="select updated_tag_list.json"
file-type="json"
title="Tags"
/>
</div>
</div>
</template>
<style scoped>
</style>
```

feat(frontend): implement fully designed upload button (SCRUM-144)

---

Frontend/error.vue
Frontend/nuxt.config.js
Frontend/pages/[...slug].vue
Frontend/server/api/index.get.ts
Frontend/server/api/proxy/[...path].ts
Frontend/server/api/users/[id]/blocks/[blockedId]/index.delete.ts
Frontend/server/api/users/[id]/blocks/index.get.ts
Frontend/server/api/users/[id]/blocks/index.post.ts
Frontend/server/api/users/[id]/index.delete.ts
Frontend/server/api/users/[id]/index.get.ts
Frontend/server/api/users/[id]/index.patch.ts
Frontend/server/api/users/[id]/tags/index.get.ts
Frontend/server/api/users/[id]/tags/index.put.ts
Frontend/server/api/users/[id]/with-relations/index.get.ts
Frontend/server/api/users/check-registration/index.get.ts
Frontend/server/api/users/index.get.ts
Frontend/server/api/users/index.post.ts
Frontend/server/api/users/search/by-email.get.ts
Frontend/server/api/users/search/by-first-name.get.ts
Frontend/server/api/users/search/by-last-name.get.ts
Frontend/server/api/users/search/by-tag.get.ts
Frontend/server/api/users/search/by-tags.get.ts
Frontend/server/middleware/logger.ts
Frontend/server/utils/fetchNest.ts
Frontend/shared/validationSchemas/validationSchemas.ts

I will add the remaining routes as well, and then we can switch fully away from the proxy.
This is the first part, the other routes will be added as well. this will provide us with extra validation, security, type safety (should we implement interfaces), nicer pending states, and more flexibility on other side effects (such as email sending, file parsing etc.)
paste this into wherever you like (index.vue if you are not logged in to see the auth checks still working, or a new /playground page when you are logged in):
```vue
<template>
<div class="max-w-xl flex flex-col items-center m-auto gap-8">
<div class="join">
<div>
<select v-model="httpMethod" class="select select-bordered join-item">
<option value="GET">GET</option>
<option value="POST">POST</option>
<option value="PUT">PUT</option> …
```

feat(frontend): Add all user routes to Nuxt API (SCRUM-146)

---

backend/src/modules/matching/entity/match.entity.ts
backend/src/modules/matching/matching.service.spec.ts
backend/src/modules/matching/matching.service.ts
backend/src/modules/supervisors/supervisors.service.ts

add supervisorId to return type for the matching service, so the frontend can easily create new supervision requests

feat(backend): add supervisorId to match entity (SCRUM-160)

---

Frontend/components/AppHeader/AppHeader.vue
Frontend/components/BottomNav/BottomNav.test.ts
Frontend/components/BottomNav/BottomNav.vue

you can switch around the amount of buttons to see how it looks.
index.vue:
```vue
<template>
<div class="flex flex-col items-center px-2 max-w-full">
<div class="min-h-screen flex flex-col max-w-7xl w-full">
<AppHeader show-user show-search/>
<StatusBar :step=1 class="mt-4"/>
<div class="my-auto mx-auto max-w-7xl w-full">
<ActionCard
button-text="Start Matching!"
card-type="primary"
>
<div class="flex flex-col items-center my-8" >
<CardStack>
<SupervisorCard
:current-capacity=12
:max-capacity=24
:similarity-score=69
:pending-amount=7
:tags="['Machine Learning', 'Artificial Intelligence', 'Web Development']"
last-name="Seidl"
first-name="Markus"
image="https://img.daisyui.com/images/stock/photo-1534528741775-53994a69daeb.webp"
/>
</CardStack>
</div>
</ActionCard>
</div>
<div …
```

refactor(frontend): move nav Buttons to props to be more reusable (SCRUM-143)

---

Frontend/middleware/01.routing.global.ts
Frontend/pages/admin/data-protection.vue
Frontend/pages/admin/settings.vue
Frontend/pages/onboarding/onboarding.vue
Frontend/pages/onboarding/student.vue
Frontend/pages/onboarding/supervisor.vue
Frontend/pages/profiles/[id].vue
Frontend/pages/student/dashboard.vue
Frontend/pages/student/data-protection.vue
Frontend/pages/student/matching.vue
Frontend/pages/student/profile.vue
Frontend/pages/student/requests.vue
Frontend/pages/student/settings.vue
Frontend/pages/supervisor/currently-supervising.vue
Frontend/pages/supervisor/dashboard.vue
Frontend/pages/supervisor/data-protection.vue
Frontend/pages/supervisor/matching.vue
Frontend/pages/supervisor/profile.vue
Frontend/pages/supervisor/settings.vue
Frontend/server/api/extended/current-user.get.ts
Frontend/shared/enums/enums.ts
Frontend/shared/types/userInterfaces.ts
Frontend/stores/useRegistrationStore.ts
Frontend/stores/useUserStore.ts

Added:
- all routes we will need (if i didnt miss any)
- middleware checks that check these routes
- additional nuxt API entpoint to get the currently signed in user (gets used in the middleware / userStore to make sure the userData is fresh and from the server when middleware runs)
- enums for userRoles and HTTP Methods to prevent errors

feat(frontend): add all (empty) routes and adjust middleware (SCRUM-170)

---

backend/OpenAPI.json
backend/src/modules/users/users.controller.ts

update `userId` route params to be `id` and make descriptions clearer

refactor(backend): standardize route params to id in users module (SCRUM-166)

---

Frontend/components/MiniCard/MiniCard.vue
Frontend/pages/student/matching.vue
Frontend/pages/supervisor/dashboard.vue
Frontend/pages/supervisor/matching.vue
Frontend/shared/types/supervisorInterfaces.ts
Frontend/shared/types/userInterfaces.ts
Frontend/stores/useSupervisorStore.ts

Main feature:
- Supervision requests page added for supervisors
Additional points addressed in this PR:
- Fixed known bug where spamming  an action (confirm/dismiss) would lose some of the requests
- Bug fixed in both supervisor and students pages
For a follow up to make some non-urgent fixes, look at task #173 (add to it if any findings are made)
https://superiorteambuilding.atlassian.net/browse/SCRUM-173

Scrum 141 frontend combine components and create working requests page for supervisors

---

Frontend/components/FileDownload/FileDownload.vue
Frontend/components/UnsafeFileInput/UnsafeFileInput.vue
Frontend/pages/admin/dashboard.vue
Frontend/pages/admin/delete.vue
Frontend/pages/admin/download.vue
Frontend/pages/admin/upload.vue
Frontend/plugins/fontawesome.js
Frontend/server/api/supervisors/index.get.ts
Frontend/shared/types/StudentInterfaces.ts
Frontend/shared/types/requests.ts
Frontend/shared/types/supervisorInterfaces.ts
Frontend/utils/csvHelpers.ts

To test, you need to log in with an admin account, and the Files you want to upload

feat(frontend): add dynamic dashboard, download, export pages (SCRUM-117)

---

Frontend/components/AdminHeader/AdminHeader.vue
Frontend/components/Avatar/Avatar.vue
Frontend/components/Profile/PictureUpload.vue
Frontend/components/inputField/InputField.vue
Frontend/components/inputField/TextArea.vue
Frontend/error.vue
Frontend/i18n/locales/de-DE.json
Frontend/i18n/locales/en-GB.json
Frontend/pages/admin/profile.vue
Frontend/pages/student/dashboard.vue
Frontend/pages/student/profile.vue
Frontend/pages/supervisor/profile.vue
Frontend/plugins/fontawesome.js
Frontend/stores/useStudentStore.ts
Frontend/stores/useUserStore.ts

Create edit view for profile. Can be found under: student / supervisor / admin: profile.vue

feat(Frontend): create profile edit view (SCRUM-130)

---

Frontend/components/AdminHeader/GenericHeader.vue
Frontend/components/CustomTag/CustomTag.test.js
Frontend/components/CustomTag/CustomTag.vue
Frontend/components/MultiStepForm/MultiStepForm.test.js
Frontend/components/MultiStepForm/MultiStepForm.vue
Frontend/components/TagPriority/TagPriority.vue
Frontend/components/TagSelector/TagSelector.test.js
Frontend/components/TagSelector/TagSelector.vue
Frontend/components/inputField/InputField.vue
Frontend/i18n/locales/de-DE.json
Frontend/i18n/locales/en-GB.json
Frontend/i18n/locales/es-ES.json
Frontend/i18n/locales/fr-FR.json
Frontend/i18n/locales/it-IT.json
Frontend/pages/onboarding/student.vue
Frontend/pages/onboarding/supervisor.vue
Frontend/plugins/fontawesome.js
backend/OpenAPI.json
backend/README.md

Partially improve the css for the tag selection. Sadly, it's still kinda broken. This needs to be re-visited once the layouting is done.
Also improved the style of the tag-selector. Also improved the way the buttons get their text and added bottom description text.
The navbar is still fucked. But I think this should be handled with layouting

feat(frontend): Fix tag selection css & improve logon css (SCRUM-206)

---

Frontend/components/MultiStepForm/MultiStepForm.vue
Frontend/i18n/locales/de-DE.json
Frontend/i18n/locales/en-GB.json
Frontend/pages/index.vue
Frontend/pages/onboarding/student.vue
Frontend/pages/onboarding/supervisor.vue

Can be tested in both the supervisor and student onboarding pages. Try to move to to the next step without filling any information/selecting tags

Scrum 225 frontend force user to select at least one tag in the onboarding

---

Frontend/components/TagSelector/TagSelector.vue
Frontend/i18n/locales/de-DE.json
Frontend/i18n/locales/en-GB.json
Frontend/pages/onboarding/onboarding.vue
Frontend/pages/onboarding/student.vue
Frontend/pages/student/edit-tags.vue
Frontend/pages/student/profile.vue
Frontend/pages/supervisor/edit-tags.vue
Frontend/pages/supervisor/profile.vue

Added the tag edit to the profile... not much more to say

feat(Frontend): add tag edit (SCRUM-256)

---

Frontend/components/AdminHeader/AdminHeader.vue
Frontend/components/AppHeader/AppHeader.test.js
Frontend/components/AppHeader/AppHeader.vue
Frontend/components/CustomTag/CustomTag.vue
Frontend/components/MiniCard/MiniCard.vue
Frontend/components/Skeleton/SkeletonSupervisorCard.vue
Frontend/components/SupervisorCard/SupervisorCard.vue
Frontend/components/inputField/InputField.vue
Frontend/i18n/locales/de-DE.json
Frontend/i18n/locales/en-GB.json
Frontend/layouts/AdminBaseLayout.vue
Frontend/layouts/Default.vue
Frontend/layouts/SearchLayout.vue
Frontend/layouts/StudentBaseLayout.vue
Frontend/layouts/SupervisorBaseLayout.vue
Frontend/pages/student/search.vue
Frontend/pages/supervisor/dashboard.vue
Frontend/pages/supervisor/search.vue
Frontend/plugins/fontawesome.js

Implement a sexy looking Serach. Yes. You may kiss my feet for this!
Also: Saw heshams note: "Please dont over-comnplicate it. Maybe one ref check (as jonas suggested)" and chose to ignore it when it comes to fanciness, but kept it very simple

feat(Frontend): implement Search (SCRUM-216)

---

Frontend/components/TagSelector/TagSelector.vue
Frontend/components/inputField/TextArea.vue
Frontend/i18n/locales/de-DE.json
Frontend/i18n/locales/en-GB.json
Frontend/nuxt.config.js
Frontend/package-lock.json
Frontend/package.json
Frontend/pages/index.vue
Frontend/pages/student/dashboard.vue
Frontend/pages/student/matching.vue
Frontend/pages/student/profile.vue
Frontend/pages/supervisor/matching.vue
Frontend/pages/supervisor/profile.vue

We can now finally use the matching page as it should be

fix(frontend) Fix swipeContainer not being scrollable and other minor css things (SCRUM-254)

---

Frontend/nuxt.config.js

Difficult PR, not sure if its reviewable

feat(Frontend): add app title (SCRUM-285)

---

Frontend/components/SideDrawer/SideDrawer.vue
Frontend/i18n/locales/de-DE.json
Frontend/i18n/locales/en-GB.json
Frontend/layouts/GenericBackLayout.vue
Frontend/package-lock.json
Frontend/package.json
Frontend/pages/admin/new-cycle.vue
Frontend/plugins/fontawesome.js
Frontend/shared/types/userInterfaces.ts

- Implement new cycle option for admin (in side drawer)
- Fix drawer:

feat(Frontend): add new cycle option for admin and fix drawer UI & Implementaiton (SCRUM-210)

---

Frontend/components/AdminHeader/AdminHeader.vue
Frontend/components/SupervisorStudentList/ValidatedMailInput.vue
Frontend/components/Toast/Toast.vue
Frontend/components/inputField/InputField.vue
Frontend/i18n/locales/de-DE.json
Frontend/i18n/locales/en-GB.json
Frontend/layouts/GenericBackLayout.vue
Frontend/pages/admin/add-admin.vue
Frontend/pages/admin/dashboard.vue

Not much more to say. It works...

fix(Frontend): add add admin logic (SCRUM-306)

---

Frontend/i18n/locales/de-DE.json
Frontend/i18n/locales/en-GB.json
Frontend/pages/admin/dashboard.vue
Frontend/pages/admin/delete.vue
Frontend/server/api/admin/users/[id]/reset.delete.ts

Admin can delete users via button

feat(frontend): add delete button  (SCRUM-312)
